## Multiples of 3

#### Problem Statement:
Given an integer array of size 10. Print the index of elements which ar multiple of 3.<br>
<br>
__Note:__ Generate the following array<br>
array([1,3,5,7,9,11,13,15,17,19]) <br>
<br>
Print the index of elements

#### Output Format:
index1 index2 index3....

In [1]:
import numpy as np

In [6]:
a = np.arange(1,20,2)
a

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [7]:
b = np.where(a % 3 == 0)
print(b)

(array([1, 4, 7], dtype=int64),)
