# Numpy

## Create Numpy Array

In [2]:
import numpy as np

1. __np.array(object, dtype=None, *, copy=True, order='K', subok=False, ndmin=0,
      like=None)__

In [3]:
a = [1,2,3]
b = np.array(a)
print(b)
print(type(b))

[1 2 3]
<class 'numpy.ndarray'>


In [5]:
a = [1,2,3,'5','a',4.5]
b = np.array(a) # numpy array can only contains homogenous elements
print(b)

['1' '2' '3' '5' 'a' '4.5']


In [10]:
a = [1,2,3,'5',4.5]
b = np.array(a, dtype = str) 
print(b)

['1' '2' '3' '5' '4.5']


In [11]:
a = [1,2,3,'5',4.5]
b = np.array(a * 3) 
print(b)

['1' '2' '3' '5' '4.5' '1' '2' '3' '5' '4.5' '1' '2' '3' '5' '4.5']


2. __np.ones(shape, dtype=None, order='C', *, like=None)__:Return a new array of given shape and type, filled with ones.
<br>
3. __np.zeros(shape, dtype=float, order='C', *, like=None)__:Return a new array of given shape and type, filled with zeros.
<br>
4. __np.full(shape, fill_value, dtype=None, order='C', *, like=None)__:Return a new array of given shape and type, filled with `fill_value`.
<br>
5. __np.empty(shape, dtype=float, order='C', *, like=None)__:Return a new array of given shape and type, without initializing entries.

In [15]:
b = np.ones(3, dtype = int)
b

array([1, 1, 1])

In [18]:
b = np.ones((2,3), dtype=int)
b

array([[1, 1, 1],
       [1, 1, 1]])

In [17]:
b = np.zeros(3, dtype = int)
b

array([0, 0, 0])

In [19]:
b = np.zeros((3,4), dtype=int)
b

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [22]:
b = np.full(3, 5, dtype=float)
b

array([5., 5., 5.])

In [23]:
b = np.full((3,3), 5, dtype=float)
b

array([[5., 5., 5.],
       [5., 5., 5.],
       [5., 5., 5.]])

In [25]:
b = np.empty((2,4))
b

array([[0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000],
       [0.00000000e+000, 6.42285340e-321, 2.22520559e-306,
        0.00000000e+000]])

6. __np.arange([start,] stop[, step,], dtype=None, *, like=None)__:Return evenly spaced values within a given interval.
7. __np.linspace(start,
    stop,
    num=50,
    endpoint=True,
    retstep=False,
    dtype=None,
    axis=0)__: Return evenly spaced numbers over a specified interval.

In [26]:
b = np.arange(10)
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [28]:
b = np.arange(2,10)
b

array([2, 3, 4, 5, 6, 7, 8, 9])

In [29]:
b = np.arange(2,20,2)
b

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [30]:
b = np.linspace(2,10)
b

array([ 2.        ,  2.16326531,  2.32653061,  2.48979592,  2.65306122,
        2.81632653,  2.97959184,  3.14285714,  3.30612245,  3.46938776,
        3.63265306,  3.79591837,  3.95918367,  4.12244898,  4.28571429,
        4.44897959,  4.6122449 ,  4.7755102 ,  4.93877551,  5.10204082,
        5.26530612,  5.42857143,  5.59183673,  5.75510204,  5.91836735,
        6.08163265,  6.24489796,  6.40816327,  6.57142857,  6.73469388,
        6.89795918,  7.06122449,  7.2244898 ,  7.3877551 ,  7.55102041,
        7.71428571,  7.87755102,  8.04081633,  8.20408163,  8.36734694,
        8.53061224,  8.69387755,  8.85714286,  9.02040816,  9.18367347,
        9.34693878,  9.51020408,  9.67346939,  9.83673469, 10.        ])

In [32]:
# checking whether step values are same or not
print(b[1] - b[0])
print(b[3] - b[2])

0.16326530612244916
0.16326530612244916


In [35]:
b = np.linspace(2,10,5, dtype = int)
b

array([ 2,  4,  6,  8, 10])

In [37]:
# making the 'stop' exclusive by putting endpoint=False
b = np.linspace(2,10,5, dtype = int, endpoint = False)
b

array([2, 3, 5, 6, 8])

8. __np.identity(n, dtype=None, *, like=None)__: Return the identity array.
9. __np.eye(N, M=None, k=0, dtype=<class 'float'>, order='C', *, like=None)__: Return a 2-D array with ones on the diagonal and zeros elsewhere.

In [38]:
# we can only get square matrix
b = np.identity(3)
b

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [41]:
# we can get any number of rows and columns matrix
b = np.eye(3, 4)
b

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

10. __np.random.rand(d0, d1, ..., dn)__:Random values in a given shape.

In [55]:
# One random value
np.random.rand()

0.9995847578136849

In [44]:
# Uniformly distributed over the range 0 and 1
b = np.random.rand(3)
b

array([0.0740439 , 0.325608  , 0.26274353])

In [46]:
# Random numbers from 0 to 10 and not from 0 to 1
b = np.random.rand(10) * 10
b

array([9.13821994, 8.28184292, 4.82334546, 5.15004573, 4.82515454,
       8.74153258, 4.70134875, 5.35408131, 9.34730803, 5.97728504])

In [45]:
b = np.random.rand(2, 3)
b

array([[0.85981931, 0.46907042, 0.51978281],
       [0.36686125, 0.09903776, 0.86126366]])

11. __np.random.randint(low, high=None, size=None, dtype=int)__: Return random integers from `low` (inclusive) to `high` (exclusive).

In [56]:
np.random.randint(10,4)

ValueError: low >= high

In [47]:
b = np.random.randint(2, size=10)
b

array([0, 1, 1, 1, 0, 0, 0, 0, 1, 0])

In [48]:
b = np.random.randint(1, size=10)
b

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [50]:
b = np.random.randint(5, size=(2,4))
b

array([[0, 2, 1, 3],
       [0, 4, 0, 4]])

In [52]:
b = np.random.randint(1, [3,5,10])
b

array([2, 1, 6])

12. __np.shape(a)__: Return the shape of an array.

In [53]:
b = np.array([0,1,2,3])
b.shape

(4,)

## Slicing & Indexing

In [1]:
import numpy as np

In [2]:
li = [1, 2, 3, 4, 5]
arr = np.array(li)

print(li)
print(arr)

[1, 2, 3, 4, 5]
[1 2 3 4 5]


__ndarray.strides :__ Tuple of bytes to step in each dimension when traversing an array.

The byte offset of element (i[0], i[1], ..., i[n]) in an array a is:

__offset = sum(np.array(i) * a.strides)__

In [3]:
print(arr.data)
print(arr.shape)
print(arr.dtype)
print(arr.strides)

(5,)
int32
(4,)


In [10]:
print(li[3])
print(arr[3])
print(li[1:4])
print(arr[1:4])

4
4
[2, 3, 4]
[2 3 4]


In [7]:
li_2d = [[1,2,3,4], [5,6,7,8], [9,10,11,12], [13,14,15,16]]
arr_2d = np.array(li_2d)

print(li_2d)
print(arr_2d)

[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [8]:
print(arr_2d.data)
print(arr_2d.shape)
print(arr_2d.dtype)
print(arr_2d.strides)

(4, 4)
int32
(16, 4)


In [12]:
print(li_2d[2][1])
print(arr_2d[2][1])
print(arr_2d[2, 1])

10
10
10


In [14]:
# Row number is fixed
print(li_2d[1][0:3])
print(arr_2d[1, :3])

[5, 6, 7]
[5 6 7]


In [18]:
x = li_2d[0:3]
print(x)
y = x[2]
print(y)

[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]
[9, 10, 11, 12]


In [16]:
print(li_2d[0:3][2])

[9, 10, 11, 12]


In [20]:
print(li_2d[0:3][3])

IndexError: list index out of range

In [19]:
print(arr_2d[0:3, 2])

[ 3  7 11]


In [21]:
print(arr_2d[2:4, 1:3])

[[10 11]
 [14 15]]


In [22]:
print(li_2d[2:4][1:3])

[[13, 14, 15, 16]]


## Mathematical Operations-1D

In [23]:
import numpy as np

In [24]:
li = [1,2,3,4,5]
a = np.random.randint(1,20,5)
b = np.random.randint(1,20,5)

print(li)
print(a)
print(b)

[1, 2, 3, 4, 5]
[ 9  3  2 17 15]
[13  2  7 17 17]


In [26]:
li = [i+1 for i in li]
li

[3, 4, 5, 6, 7]

In [27]:
# Addition of each element
a = a + 1
a

array([10,  4,  3, 18, 16])

In [28]:
# Addition of two numpy arrays
c = a + b
c

array([23,  6, 10, 35, 33])

In [29]:
# Subtraction
d = a - b
d

array([-3,  2, -4,  1, -1])

In [30]:
# Multiplication
e = a * b
e

array([130,   8,  21, 306, 272])

In [31]:
# Division
f = a / b
f

array([0.76923077, 2.        , 0.42857143, 1.05882353, 0.94117647])

In [32]:
# Floor Division
g = a // b
g

array([0, 2, 0, 1, 0], dtype=int32)

In [33]:
# Exponentiation
h = a ** b
h

array([1316134912,         16,       2187, 1695678464,          0],
      dtype=int32)

1. __sum()__
2. __mean()__
3. __min()__
4. __argmin()__: find the index of the minimum element
5. __max__()__
6. __argmax()__: find index of maximum element

In [35]:
print(a)
print(a.sum())
print(a.mean())
print(a.min())
print(a.argmin())
print(a.max())
print(a.argmax())

[10  4  3 18 16]
51
10.2
3
2
18
3


In [37]:
print(a)
print(b)

[10  4  3 18 16]
[13  2  7 17 17]


In [38]:
a > b

array([False,  True, False,  True, False])

In [39]:
a < b

array([ True, False,  True, False,  True])

In [40]:
a == b

array([False, False, False, False, False])

1.__logical_or()__<br>
2.__logical_and()__<br>
3.__logical_not()__<br>

In [41]:
print(np.logical_or(a, b))
print(np.logical_and(a, b))

[ True  True  True  True  True]
[ True  True  True  True  True]


In [43]:
a[2] = 0
print(a)
print(np.logical_not(a))

[10  4  0 18 16]
[False False  True False False]


## Boolean Indexing

In [44]:
import numpy as np

In [45]:
a = np.array(['t','b','r','d','e','f','z','a'])
b = np.random.randint(1, 20, 8)

print(a)
print(b)

['t' 'b' 'r' 'd' 'e' 'f' 'z' 'a']
[12  4  1  4  4  3  4  1]


In [46]:
print(b > 10)

[ True False False False False False False False]


In [48]:
bool_arr = b > 10
print(bool_arr)
new_arr = b[bool_arr] # extracts only those elements which are true
print(new_arr)

[ True False False False False False False False]
[12]


In [49]:
new_arr = b[b > 10]
new_arr

array([12])

In [50]:
new_arr = b[(b > 10) & (b < 18)]
new_arr

array([12])

In [52]:
print(b)
c = b
c

[12  4  1  4  4  3  4  1]


array([12,  4,  1,  4,  4,  3,  4,  1])

In [55]:
c[:3] = 19  # updating multiple elements in one go
print(c)
c[c > 15] = 100
c

[19 19 19  4  4  3  4  1]


array([100, 100, 100,   4,   4,   3,   4,   1])

__np.where(condition, [x, y])__ :Return elements chosen from `x` or `y` depending on `condition`.

In [56]:
print(b)

[100 100 100   4   4   3   4   1]


In [57]:
print(b[b == 100])

[100 100 100]


In [58]:
ind = np.where(b == 100)
ind

(array([0, 1, 2], dtype=int64),)

In [59]:
print(a)
print(b)

['t' 'b' 'r' 'd' 'e' 'f' 'z' 'a']
[100 100 100   4   4   3   4   1]


In [63]:
ind = np.where(b == 100)
print(ind)
print(a[ind])

(array([0, 1, 2], dtype=int64),)
['t' 'b' 'r']


## Boolean Indexing-2D

In [64]:
import numpy as np

In [65]:
a = np.random.randint(1,30, (5,6))
print(a)

[[13 28 13 24  1  7]
 [21 17  7 15 18 14]
 [12 22 10 28  3  7]
 [19  8  5 23  9  2]
 [21 23  4  2 25  2]]


In [67]:
bool_arr = a > 20
print(bool_arr)

[[False  True False  True False False]
 [ True False False False False False]
 [False  True False  True False False]
 [False False False  True False False]
 [ True  True False False  True False]]


In [68]:
ans = a[bool_arr]
print(ans)

[28 24 21 22 28 23 21 23 25]


In [69]:
b = a
print(a)

[[13 28 13 24  1  7]
 [21 17  7 15 18 14]
 [12 22 10 28  3  7]
 [19  8  5 23  9  2]
 [21 23  4  2 25  2]]


In [70]:
b[bool_arr] = 100
print(b)

[[ 13 100  13 100   1   7]
 [100  17   7  15  18  14]
 [ 12 100  10 100   3   7]
 [ 19   8   5 100   9   2]
 [100 100   4   2 100   2]]


In [71]:
c = np.random.randint(1,10,(2,2))
print(c)

[[2 9]
 [1 3]]


In [72]:
c_bool = np.array([[True, False], [False, True], [True, True]])
print(c_bool)

[[ True False]
 [False  True]
 [ True  True]]


In [73]:
print(c(c_bool))

TypeError: 'numpy.ndarray' object is not callable

In [74]:
print(b)

[[ 13 100  13 100   1   7]
 [100  17   7  15  18  14]
 [ 12 100  10 100   3   7]
 [ 19   8   5 100   9   2]
 [100 100   4   2 100   2]]


In [75]:
bool_arr = b[:, 3] == 100
print(bool_arr)

[ True False  True  True False]


In [76]:
# To update a specifice column over numpy array
# b[row which are true, column]
b[bool_arr, 3] = 99
print(b)

[[ 13 100  13  99   1   7]
 [100  17   7  15  18  14]
 [ 12 100  10  99   3   7]
 [ 19   8   5  99   9   2]
 [100 100   4   2 100   2]]


## Broadcasting

Numpy Arrays of unequal sizes

In [77]:
import numpy as np

Same dimensions: __Type Compatible__

In [79]:
x = np.random.randint(1, 10, (3,3))
y = np.random.randint(1, 10, (3,3))
print(x)
print('\n')
print(y)

[[9 8 7]
 [7 1 1]
 [2 4 5]]


[[3 7 2]
 [3 9 1]
 [3 3 6]]


In [80]:
ans = x - y
print(ans)

[[ 6  1  5]
 [ 4 -8  0]
 [-1  1 -1]]


dimensions with one of them is 1: __Type Compatible__

In [85]:
x = np.random.randint(1, 10, (3,3))
y = np.random.randint(1, 10, (3))
print(x)
print('\n')
print(y)

[[1 4 8]
 [5 5 6]
 [5 7 1]]


[7 8 3]


In [87]:
# in y matrix the row is repeated 3 times and 
# then it is subtracted
ans = x - y
print(ans)

[[-6 -4  5]
 [-2 -3  3]
 [-2 -1 -2]]


Unequal dimension: __Not Type Compatible__

In [88]:
x = np.random.randint(1, 10, (3,2))
y = np.random.randint(1, 10, (2,3))
print(x)
print('\n')
print(y)

[[6 8]
 [2 4]
 [8 3]]


[[4 4 9]
 [9 2 4]]


In [89]:
ans = x - y
print(ans)

ValueError: operands could not be broadcast together with shapes (3,2) (2,3) 

#### Transposing the array

In [90]:
y = np.transpose(y)
print(y)
print('\n')
ans = x - y
print(ans)

[[4 9]
 [4 2]
 [9 4]]


[[ 2 -1]
 [-2  2]
 [-1 -1]]
