## Replace Max

#### Problem Statement:
Given an integer array of size 10 and replace the first occurrence of maximum value by 0.<br>
<br>
__Note:__ Generate the following array<br>
array([11,2,13,4,15,6,27,8,19]) <br>
<br>
Print the Numpy array

#### Output Format:
firstElement 
secondElement 
...

In [1]:
import numpy as np

In [3]:
a = np.array([11,2,13,4,15,6,27,8,19])
a

array([11,  2, 13,  4, 15,  6, 27,  8, 19])

In [4]:
a[a.argmax()] = 0
a

array([11,  2, 13,  4, 15,  6,  0,  8, 19])