In [1]:
# importing the libraries
import numpy as np
from sklearn.preprocessing import StandardScaler, scale

In [2]:
# Dummy numpy array
X = np.array([[1., -1., 2.],
              [2., 0., 0.],
              [0., 1.,-1.]])

In [3]:
# centers it around the mean i.e it makes the variance = 0
X_scaled = scale(X) 
X_scaled

array([[ 0.        , -1.22474487,  1.33630621],
       [ 1.22474487,  0.        , -0.26726124],
       [-1.22474487,  1.22474487, -1.06904497]])

In [4]:
# makes the mean = 0
X_scaled.mean(axis = 0) 

array([0., 0., 0.])

In [5]:
# makes the standard deviation or variance = 1
X_scaled.std(axis = 0) 

array([1., 1., 1.])

In [6]:
# Using the Standard Scaler
scaler = StandardScaler()
scaler.fit(X)

scaler.transform(X)

array([[ 0.        , -1.22474487,  1.33630621],
       [ 1.22474487,  0.        , -0.26726124],
       [-1.22474487,  1.22474487, -1.06904497]])

In [7]:
X_test = [[1,1,0]]
scaler.transform(X_test)

array([[ 0.        ,  1.22474487, -0.26726124]])